In [2]:
import numpy as np
import sympy as sp

In [8]:
a = np.matrix([
    [1,2],
    [3,4]
])

eig, eig_vec = np.linalg.eig(a)
print("eigen values",eig)
print("eigen values",eig_vec)

eigen values [-0.37228132  5.37228132]
eigen values [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [11]:
print(np.linalg.matrix_rank(a))

2


In [12]:
print(np.linalg.det(a))

-2.0000000000000004


In [15]:
b = np.matrix([
    [0,2,5],
    [0,4,0]
])

total_elements =  b.size
zeros = np.count_nonzero(b == 0)
sparsity  = zeros/total_elements
print(sparsity)

0.5


In [16]:
matrix1 = np.random.randint(0,21,size=(3,3))
matrix2 = np.random.randint(0,21,size=(3,3))

add = matrix1 + matrix2
multiply = matrix1 * matrix2
transpose = np.transpose(multiply)
print(add)
print(multiply)
print(transpose)

[[14 28 34]
 [19 11 22]
 [19 15 25]]
[[ 24 180 280]
 [ 90  28 120]
 [ 60  44 114]]
[[ 24  90  60]
 [180  28  44]
 [280 120 114]]


In [6]:
# m = np.random.randint(0,21,size=(3,3))
# diagonal = np.diag(m)
m = [1,2,3]
diagonal_met = np.diagflat(m)
print(diagonal_met)


[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
a = np.array([1,2,3])
b = np.array([5,6,7])
k = 2
#  k(a+b) = k.a + k.b
p1 = np.multiply(k,np.add(a,b))
p2 = np.add(np.multiply(k,a),np.multiply(k,b))
print(f"{p1} \n\n {p2}")

[12 16 20] 

 [12 16 20]


In [ ]:
# (k+l)*v1 = k*v1 + l*v1